[shell]
program = "/bin/zsh"
args = ["-l","-c","tmux a -t default || tmux new -s default"]

[env]
  TERM= "xterm-256color"

[font]
size = 12

[font.normal]
  family = "JetBrainsMono Nerd Font Mono"

[window]
  decorations = "none"
  opacity= 0.85

[window.padding]
  x = 7
  y = 7


